version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - printenv
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ./build.sh
cache:
  paths:
    - '/var/lib/docker/**/*'
