# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(default=datetime.datetime.now)),
                ('device', models.CharField(max_length=100)),
                ('delta', models.CharField(max_length=500000)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Trunk'),
        ),
    ]
