# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='delta',
            field=models.TextField(),
        ),
    ]
